# Config file for automatic testing at travis-ci.org
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  
# command to install dependencies
install: "pip install -r travis_requirements.txt"

script:
  - pip freeze
  - make dist
  - pip install ./dist/bubble-*-py2.py3-none-any.whl
  - python --version
  - bubble --version
  - behave
  - pip freeze
