# Config file for automatic testing at travis-ci.org
language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  
# command to install dependencies
install: "pip install -r travis_requirements.txt"

script:
  - pip freeze
  - pip install bubble
  - pip install ./demo_client/mydumboclient_site_packages.mydumboclient/dist/bubble_dumbo_client-0.0.1-py2.py3-none-any.whl
  - pip install ./demo_client/mydummyclient_bubble.clients.mydummyclient/dist/bubble_dummy_client-0.0.1-py2.py3-none-any.whl
  - pip freeze
  - python --version
  - bubble --version
  - behave
  - pip freeze
