# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r travis_requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - make dist
  - pip install ./dist/bubble-*-py2.py3-none-any.whl
  - behave --format=progress
