# Config file for automatic testing at travis-ci.org
language: python
env:
  - TOXENV=docs
  - TOXENV=flake8
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=pypy
install:
  - pip install tox
  
script:
  - pip install -r travis_requirements.txt
  - make dist
  - pip install ./dist/bubble-*-py2.py3-none-any.whl
  - behave
