---
CFG:
    BUBBLE:
        DEBUG: True
        VERBOSE: True
        STORAGE_TYPE: json
    DEV:
        SOURCE:    #pull
            CLIENT: ./mysrcclient.py
        TRANSFORM:
            UNIQ_KEYS_PULL: id
            DELTAS_ONLY: False
            RULES: config/rules.bubble
        TARGET:    #push
            CLIENT: dummy
            URL: http://localhost:8002
...
